#define TK_EOF                              1
#define TK_NEWLINE                          2
#define TK_COMMA                            3
#define TK_SEMI                             4
#define TK_L_PAREN                          5
#define TK_R_PAREN                          6
#define TK_L_BRACKET                        7
#define TK_R_BRACKET                        8
#define TK_L_BRACE                          9
#define TK_R_BRACE                         10
#define TK_STRING_LIT                      11
#define TK_RAW_STRING_LIT                  12
#define TK_IDENTIFIER                      13
#define TK_PACKAGE                         14
#define TK_IMPORT                          15
#define TK_VAR                             16
#define TK_CONST                           17
#define TK_TYPE                            18
#define TK_STRUCT                          19
#define TK_FUNC                            20
#define TK_RETURN                          21
#define TK_FOR                             22
#define TK_BREAK                           23
#define TK_CONTINUE                        24
#define TK_IF                              25
#define TK_ELSE                            26
#define TK_SWITCH                          27
#define TK_CASE                            28
#define TK_DEFAULT                         29
