/* Generated by re2c 4.0.2 on Tue Apr  8 02:16:38 2025 */
#line 1 "omega/scanner.c.in"
// Copyright (C) 2020, Skyler. All rights reserved.
// Use of this source code is governed by the MIT license that can be
// found in the LICENSE file.

#include "omega/scanner.h"

void omg_scanner_init(omg_scanner* scanner) {
}

omg_token omg_scanner_scan(omg_scanner* scanner) {
  #line 13 "omega/scanner.c.in"

}
