/* Generated by re2c 4.0.2 on Sun Apr 20 17:11:52 2025 */
#line 1 "omega/scanner.re"
// Copyright (C) 2020, Skyler. All rights reserved.
// Use of this source code is governed by the MIT license that can be
// found in the LICENSE file.

#include "omega/scanner.h"

#include <stddef.h>

#include "omega/token.h"

void omg_scanner_init(omg_scanner* scanner, const char* str) {
  scanner->start = str;
  scanner->cursor = scanner->start;
  scanner->marker = NULL;  // No need to initialize
  scanner->cur_line = 1;
  scanner->cur_col = 1;
}

static inline void update_location(omg_scanner* scanner, const char* token) {
  int span = (int)(scanner->cursor - token);
  scanner->cur_col += span;
}

static inline omg_token make_token(omg_scanner* scanner, const char* token, int token_type) {
  omg_token result = {
      .type = token_type,
      .pos = token - scanner->start,
      .end = scanner->cursor - scanner->start,
      .lineno = scanner->cur_line,
      .colno = scanner->cur_col,
  };
  update_location(scanner, token);
  return result;
}

#line 39 "omega/scanner.re"


omg_token omg_scanner_scan(omg_scanner* scanner) {
  const char* token;
  for (;;) {
    token = scanner->cursor;
  
#line 47 "omega/scanner.c"
{
	char yych;
	yych = *scanner->cursor;
	switch (yych) {
		case 0x00: goto yy1;
		case '\t':
		case '\v':
		case '\r':
		case ' ': goto yy4;
		case '\n': goto yy6;
		case 'b': goto yy7;
		case 'e': goto yy8;
		default: goto yy2;
	}
yy1:
	++scanner->cursor;
#line 56 "omega/scanner.re"
	{
      return make_token(scanner, token, TK_EOF);
    }
#line 68 "omega/scanner.c"
yy2:
	++scanner->cursor;
yy3:
#line 53 "omega/scanner.re"
	{
    }
#line 75 "omega/scanner.c"
yy4:
	yych = *++scanner->cursor;
	switch (yych) {
		case '\t':
		case '\v':
		case '\r':
		case ' ': goto yy4;
		default: goto yy5;
	}
yy5:
#line 67 "omega/scanner.re"
	{
      update_location(scanner, token);
      continue;
    }
#line 91 "omega/scanner.c"
yy6:
	++scanner->cursor;
#line 60 "omega/scanner.re"
	{
      omg_token result = make_token(scanner, token, TK_NEWLINE);
      scanner->cur_line++;
      scanner->cur_col = 1;
      return result;
    }
#line 101 "omega/scanner.c"
yy7:
	yych = *(scanner->marker = ++scanner->cursor);
	switch (yych) {
		case 'e': goto yy9;
		default: goto yy3;
	}
yy8:
	yych = *(scanner->marker = ++scanner->cursor);
	switch (yych) {
		case 'n': goto yy11;
		default: goto yy3;
	}
yy9:
	yych = *++scanner->cursor;
	switch (yych) {
		case 'g': goto yy12;
		default: goto yy10;
	}
yy10:
	scanner->cursor = scanner->marker;
	goto yy3;
yy11:
	yych = *++scanner->cursor;
	switch (yych) {
		case 'd': goto yy13;
		default: goto yy10;
	}
yy12:
	yych = *++scanner->cursor;
	switch (yych) {
		case 'i': goto yy14;
		default: goto yy10;
	}
yy13:
	++scanner->cursor;
#line 75 "omega/scanner.re"
	{
      return make_token(scanner, token, KW_END);
    }
#line 141 "omega/scanner.c"
yy14:
	yych = *++scanner->cursor;
	switch (yych) {
		case 'n': goto yy15;
		default: goto yy10;
	}
yy15:
	++scanner->cursor;
#line 72 "omega/scanner.re"
	{
      return make_token(scanner, token, KW_BEGIN);
    }
#line 154 "omega/scanner.c"
}
#line 78 "omega/scanner.re"

  }
}
